# This is a basic workflow to help you get started with Actions

name: Build and Deploy Application

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    deploy-infra:
        name: Deploy Azure Resources
        runs-on: ubuntu-latest
        steps:

        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
            enable-AzPSSession: true 
        
        - name: Deploy Azure Resources
          uses: azure/powershell@v1
          with: 
            azPSVersion: 7.5.0
            inlineScript: |
              $params = @{
                name = "app1";
              }

              $res = New-AzDeployment -TemplateFile "src/infra/bicep/main.bicep" -TemplateParameterObject $params -Location ${{ secrets.AZURE_REGION }}
              
              # Save the outputs from the deployment for later use
              $outputsJson = $res.Outputs | ConvertTo-Json -Depth 10
              Write-Output $outputsJson
              $outputsJson | Out-File deploymentoutput.json

    
    build-node:
        name: Build API and Frontend
        runs-on: ubuntu-latest
        
        steps:
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main

        - name: 'Setup Node'
          uses: actions/setup-node@v3
          with:
            node-version: '16'

        - name: 'Build API'
          run: |
            npm install --if-present
            npm run build --if-present
          working-directory: src/api

        - name: 'Build Frontend'
          run: |
            npm install
            npm run build        
          working-directory: src/frontend

    publish-api:
        name: Publish API to Azure Function
        needs: [deploy-infra, build-node]
        runs-on: ubuntu-latest

        steps:
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main

        - name: 'Obtain Function publish profile'
          id: func-publish-profile
          uses: azure/powershell@v1
          with: 
            azPSVersion: 7.5.0
            inlineScript: |
              $deploymentOutput = Get-Content deploymentoutput.json | ConvertFrom-Json
              $rgName = $deploymentOutput.RESOURCE_GROUP_NAME.Value
              $funcName = $deploymentOutput.FUNCTION_NAME.Value

              $profile = (az functionapp deployment list-publishing-credentials --name app1-graphqlfunc --resource-group app1-rg)
              Write-Output ::set-output name=function_publish_profile::$profile

        - name: 'Publish Azure Function'
          uses: Azure/functions-action@v1
          id: fa
          with:
            app-name: graphql
            package: src/api
            publish-profile: ${{ steps.func-publish-profile.outputs.function_publish_profile }}

    publish-web:
        name: Publish Website to Static Storage website
        needs: [deploy-infra, build-node]
        runs-on: ubuntu-latest

        steps:
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main

        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
            enable-AzPSSession: true 

        - name: 'Get storage account name'
          id: storage-name
          uses: azure/powershell@v1
          with: 
            azPSVersion: 7.5.0
            inlineScript: |
              $deploymentOutput = Get-Content deploymentoutput.json | ConvertFrom-Json
              $storageAccountName = $deploymentOutput.STORAGE_ACCOUNT_NAME.Value
              
              Write-Output ::set-output name=storage_account_name::$storageAccountName

        - name: 'Copy files to Azure Storage'
          uses: Azure/cli@v1
          with:
            inlineScript: |
              az storage blob service-properties update --account-name ${{ steps.storage-name.outputs.storage_account_name}} --static-website --404-document index.html --index-document index.html
              az storage blob upload-batch --auth-mode login --account-name ${{ steps.storage-name.outputs.storage_account_name}} --destination '$web' --source src/frontend/dist --overwrite true
